USE MASTER
GO

--MODIFICAR LA AUTORIZACIÓN PARA UN
--EL USUARIO SA COMO PROPIETARIO

ALTER AUTHORIZATION ON DATABASE::[AdventureWorksDW2014] TO sa;
GO

ALTER AUTHORIZATION ON DATABASE::[AdventureWorks2014] TO sa;
GO